[package]
name = "gr_raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.34.1"
image = "0.25.9"
rayon = "1.10.0"
clap = { version = "4.5.53", features = ["derive"] }
toml = "0.9.8"
serde = { version = "1.0.228", features = ["derive"] }
indicatif = "0.18.3"
log = "0.4.20"
env_logger = "0.11.8"
noise = "0.9"
test-log = "0.2.19"

[dev-dependencies]
approx = "0.5.1"
