color_normalization = "NoNormalization"
celestial_temperature = 0.0

[celestial_texture.Bitmap]
beaming_exponent = 3.0
path = "resources/celestial.png"
color_normalization = "NoNormalization"

[geometry_type.Euclidean]

[[objects]]

[objects.Disc]
inner_radius = 3.0
outer_radius = 5.0
temperature = 1.0

[objects.Disc.texture.Bitmap]
beaming_exponent = 3.0
path = "resources/disk.png"
color_normalization = "NoNormalization"

[[objects]]

[objects.Sphere]
radius = 3.0
position = [0.0, 0.0, 0.0]

[objects.Sphere.texture.Bitmap]
beaming_exponent = 3.0
path = "resources/sphere.png"
color_normalization = "NoNormalization"
