color_normalization = "NoNormalization"
celestial_temperature = 0.0

[celestial_texture.Bitmap]
beaming_exponent = 3.0
path = "resources/celestial.png"
color_normalization = "NoNormalization"

[geometry_type.Kerr]
radius = 1.0
a = 0.499
horizon_epsilon = 1e-4

[[objects]]

[objects.VolumetricDisc]
inner_radius = 0.795
outer_radius = 16.0
temperature = 5000.0
num_octaves = 8
max_steps = 50000
step_size = 0.0002
thickness = 0.03
density_multiplier = 500.0
brightness_reference_temperature = 1000.0
absorption = 0.3
scattering = 0.4
noise_scale = [25.0, 15.0, 40.0]
noise_offset = -0.2

[objects.VolumetricDisc.texture.BlackBody]
beaming_exponent = 7.0
color_normalization = "EqualLuminance"
